config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'assignments#index'
  resources :assignments, only: %i[index new create]
  resources :work_orders, only: %i[index show new create]
  resources :workers, only: %i[index show new create] do
    resources :work_orders, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
# frozen_string_literal: true

# The assignment model handles assignment validations and associations.
class Assignment < ApplicationRecord
  belongs_to :work_order
  belongs_to :worker

  validate :work_order_assignments_count_within_limit, on: :create
  validates_uniqueness_of :work_order_id, scope: :worker_id
  validates :work_order_id, presence: true, numericality: { only_integer: true }
  validates :worker_id, presence: true, numericality: { only_integer: true }

  def work_order_assignments_count_within_limit
    if WorkOrder.ids.include?(work_order_id)
      errors.add(:base, 'Exceeded assignment limit')\
      if work_order.assignments.count >= work_order.work_order_limit
    end
  end
end

app/models/work_order.rb
# frozen_string_literal: true

# The WorkOrder model handles work order validations and associations
class WorkOrder < ApplicationRecord
  has_many :assignments
  has_many :workers, through: :assignments

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 600 }
  validates :deadline, presence: true

  def work_order_limit
    5
  end
end

app/models/worker.rb
# frozen_string_literal: true

# The worker model handles worker validations and associations
class Worker < ApplicationRecord
  has_many :assignments
  has_many :work_orders, through: :assignments

  validates :name, presence: true, length: { maximum: 50 }
  validates :company_name, presence: true, length: { maximum: 80 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/assignments_controller.rb
# frozen_string_literal: true

class AssignmentsController < ApplicationController
  def index
    @assignments = Assignment.all
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.create(assignment_params)
    if @assignment.save
      flash[:success] = 'Assignment successfully added'
    else
      flash[:alert] = 'Assignment couldn\'t be created'
    end
    redirect_to assignments_path
  end

  private

  def assignment_params
    params.require(:assignment).permit(:work_order_id, :worker_id)
  end
end

app/controllers/work_orders_controller.rb
# frozen_string_literal: true

class WorkOrdersController < ApplicationController
  def index
    @work_orders = WorkOrder.all
  end

  def show
    @work_order = WorkOrder.find(params[:id])
  end

  def new
    @work_order = WorkOrder.new
  end

  def create
    @work_order = WorkOrder.create(work_orders_params)
    if @work_order.save
      flash[:success] = 'Work Order successfully added'
    else
      flash[:alert] = 'Work Order couldn\'t be created'
    end
    redirect_to work_orders_path
  end

  private

  def work_orders_params
    params.require(:work_order).permit(:title, :description, :deadline)
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  def index
    @workers = Worker.all
  end

  def show
    @worker = Worker.find(params[:id])
    @work_orders = @worker.work_orders.order('deadline ASC')
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.create(worker_params)
    if @worker.save
      flash[:success] = 'worker successfully created'
    else
      flash[:alert] = 'worker couldn\'t be created'
    end
    redirect_to workers_path
  end

  private

  def worker_params
    params.require(:worker).permit(:name, :company_name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/assignments_helper.rb
# frozen_string_literal: true

module AssignmentsHelper
end

app/helpers/work_orders_helper.rb
# frozen_string_literal: true

module WorkOrdersHelper
end

app/helpers/workers_helper.rb
# frozen_string_literal: true

module WorkersHelper
end

app/views/assignments/index.html.erb
<h1>Worker Assignments</h1>

<ul class="assignments">
  <% @assignments.each do |assignment| %>
    <li>
      <%= assignment.work_order.title %> - 
      <%= assignment.worker.name %>
    </li>
  <% end %>
</ul>

app/views/assignments/new.html.erb
<h1>Create Assignment</h1>

<%= form_for(@assignment) do |f| %>

<%= f.label :work_order_id %><br>
<%= f.text_field :work_order_id %><br>

<%= f.label :worker_id %><br>
<%= f.text_field :worker_id %><br><br>

<%= f.submit "Create my assignment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <nav>
      <%= link_to 'Home', root_path %> | 
      <%= link_to 'Workers', workers_path %> | 
      <%= link_to 'Work-Orders', work_orders_path %>
    </nav>
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message) %>
      <% end %>
    <%= yield %>
    </div>
    <footer>
      <%= link_to 'Create-Assignment', new_assignment_path %> | 
      <%= link_to 'Create-Worker', new_worker_path %> | 
      <%= link_to 'Create-Worker order', new_work_order_path %>
    </footer>
  </body>
</html>

app/views/shared/_work_orders.html.erb
<% if @work_orders.any? %>
  <ol>
    <% @work_orders.each do |work_order| %>
      <li>
        <%= link_to work_order.title, work_order %> - 
        <%= work_order.deadline %>
      </li>
    <% end %>
  </ol>
<% end %>

app/views/work_orders/index.html.erb
<h1>All work orders</h1>

<ul>
  <% @work_orders.each do |work_order| %>
    <li>
      <%= link_to work_order.title, work_order %>
    </li>
  <% end %>
</ul>

app/views/work_orders/new.html.erb
<h1>Create Work Order</h1>

<%= form_for(@work_order) do |f| %>

<%= f.label :title %><br>
<%= f.text_field :title %><br>

<%= f.label :description %><br>
<%= f.text_field :description %><br>

<%= f.label :deadline %><br>
<%= f.date_field :deadline %><br>

<%= f.submit "Create my work order" %>
<% end %>

app/views/work_orders/show.html.erb
<h1><%= @work_order.title %></h1>
<p><%= @work_order.deadline %></p>
<p><%= @work_order.description %></p>

app/views/workers/index.html.erb
<h1>All workers</h1>

<ul>
  <% @workers.each do |worker| %>
    <li>
      <%= link_to worker.name, worker %>
    </li>
  <% end %>
</ul>

app/views/workers/new.html.erb
<h1>Enter worker details</h1>

<%= form_for(@worker) do |f| %>

<%= f.label :name %><br>
<%= f.text_field :name %><br>

<%= f.label :company_name %><br>
<%= f.text_field :company_name %><br>

<%= f.label :email %><br>
<%= f.email_field :email %><br>

<%= f.submit "Create my worker" %>
<% end %>

app/views/workers/show.html.erb
<h1><%= @worker.name %></h1>
<p><%= render 'shared/work_orders' %></p>